//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab10 {
	
	
	public partial class DisplayUser {
		
		protected System.Web.UI.WebControls.Label lblGreeting;
		
		protected System.Web.UI.WebControls.Label lblDisplayFullName;
		
		protected System.Web.UI.WebControls.Label lblDisplayEmail;
		
		protected System.Web.UI.WebControls.Label lblDisplayAge;
		
		protected System.Web.UI.WebControls.Label lblDisplayRole;
	}
}
